version: "3"

volumes:
  app_volume: {}
  production_app_docs: {}
  production_traefik: {}

services:
  app:
    build:
      context: .
      dockerfile: ./compose/production/docusaurus/Dockerfile
    image: docusaurus_production
    container_name: docusaurus_production_app
    volumes:
      - ./app_volume:/app:z
    #    ports:
    #      - 3000:3000
    command: ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--no-open"]

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: app_production_traefik
    depends_on:
      - app
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:81:80"
      - "0.0.0.0:443:443"

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: app_production_nginx
    ports:
      - 1118:80
    depends_on:
      - app
    volumes:
      - production_app_docs:/usr/share/nginx/html/:ro